### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by 0xsmoos** [LikeToAccess/LMB#1]
Traceback (most recent call last):
  File "c:\Users\Demit\Desktop\LMB\main.py", line 100, in <module>
    scraper.run()
  File "c:\Users\Demit\Desktop\LMB\main.py", line 81, in run
    "day":         day_information[1],
IndexError: list index out of range
PS C:\Users\Demit\Desktop\LMB> [29376:29352:0324/165352.215:ERROR:device_event_log_impl.cc(214)] [16:53:52.215] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)

**Comment by 0xsmoos** [comment]
You have to accept cookies, then it will work.
